### ISSUE TITLE
json_measure seg_faults

### ISSUE THREAD

**Issue by crides** [json-parser/json-builder#12]
I was testing round-triping myself i.e. building up a object, serialize it to `char *`, parse it again, and then try to print the resulting object. But when I try to allocate buffer for the last object using `json_measure`, it seg faults.

The testing code is below:

```C
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include "json.h"
#include "json-builder.h"

json_value *create_entry_obj(char *name, char *data) {
    json_value *obj = json_object_new(0);
    json_object_push(obj, "name", json_string_new(name));
    json_object_push(obj, "data", json_string_new(data));
    json_object_push(obj, "date", json_integer_new(time(NULL)));
    return obj;
}

int main() {
    json_value *arr = json_array_new(0);
    json_array_push(arr, create_entry_obj("name1", "data1"));
    json_array_push(arr, create_entry_obj("name2", "data2"));

    int len = json_measure(arr);
    char *buf = malloc(json_measure(arr));
    json_serialize(buf, arr);
    printf("%s\n", buf);

    json_value *parsed = json_parse(buf, len);
    printf("%d, %lu\n", len, strlen(buf));
    printf("%ld\n", json_measure(parsed));
    char *buf2 = malloc(json_measure(parsed));
    printf("%s\n", buf2);
    
    free(buf);
    free(buf2);
    json_builder_free(arr);
    json_builder_free(parsed);
}
```

`gcc -v`:

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by udp** [comment]
json-parser by default doesn't allocate the extra space in json_values that json-builder needs to maintain its additional state.  Change:

     json_value *parsed = json_parse(buf, len);

to something like

    json_settings settings = {};
    settings.value_extra =  json_builder_extra;
    char err[json_error_max];
    json_value *parsed = json_parse_ex(&settings, buf, len, err);

**Comment by Crides** [comment]
Ok, I see. I have also seen that in the docs when I was looking thru the code. My bad for not rtfm... But I still have one more question before we close this issue. Why does `json-parser` need to allocate the extra space? Aren't the `json_value`s just objects that the builder builds up and the parser parses into?

**Comment by LB--** [comment]
If you look at the implementation of `json_builder_free` you can see why it is necessary:
> Names are allocated separately for builder values.  In parser values, they are part of the same allocation as the values array itself.
